### ISSUE TITLE
asserting JSON array contents in arbitrary order

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#114]
It's not unusual for JSON APIs to return arrays whose order is irrelevant (i.e effectively sets, e.g. [JSON API](http://jsonapi.org/format/)'s `data` object graph).

Testing for entries within such arrays seems tricky. In order to assert that a specific entry exists, I'm currently resorting to this:

```yaml
response_json_paths: # XXX: order currently hard-coded, but not actually relevant
    $.data[0].id: login
    $.data[0].links.self: http://example.org/login
    $.data[1].id: profiles
    $.data[1].links.self: http://example.org/profiles
    $.data[2].id: posts
    $.data[2].links.self: http://example.org/posts
```

This is brittle because order isn't guaranteed. The only alternative seems to be to use filter expressions:

```yaml
$.data[?(@.attributes.id = "login")]
```

That's not particularly readable though.

Is this something #86 could help with, perhaps via `sorted`?

**Comment by cdent** [comment]
Sort is the usual way I would think of dealing with this, but getting sort to work, either via #86 or some custom way has proven challenging to get working in a useful fashion that doesn't blow up the rest of jsonpath_rw. I think it is possible, just requires some clear brain time. Similar issues exist for filter expressions.

(There's a part of me that thinks this is all a good constraint because it encourages people to stop using this blight of anonymous dicts inside lists.)

Now that I've gotten that off my chest: Yes, I agree it is a real issue and something needs to be done.

I think the right way forward it figure out how to correctly extend jsonpath for the bonus features. I have branch laying around exploring that which I will try to bring back to life and get it up here for people to think about.

**Comment by cdent** [comment]
This has become more urgent as a result of starting testing on Nova. I'm not quite sure how to proceed though as I'm struggling to find something that actually works...
