### ISSUE TITLE
Tests fails in environment without internet access

### ISSUE THREAD

**Issue by amoralej** [cdent/gabbi#133]
When executing tests in an envionment without access to internet (as in controlled packaging environments), following tests fail:

FAIL: gabbi.driver.test_intercept_google_follow_redirects.test_request
FAIL: gabbi.driver.test_intercept_google_google.test_request
FAIL: gabbi.driver.test_intercept_google_google_russia.test_request
FAIL: gabbi.driver.test_live_google_google.test_request
FAIL: gabbi.driver.test_live_google_follow_redirects.test_request

I think unit tests shouldn't require access to external resources to be executed but mock them.

**Comment by cdent** [comment]
Thanks for reporting this.

I can move those to their own file that uses a fixture to skip them and will only turn them on if an environment variable is set. The reason for doing that is because those tests are there to explicitly exercise the full stack (all the way down into the real sockets).

Does that seem like a reasonable solution? I've done a similar thing in wsgi-intercept to avoid real network contact for packaging contexts.

What follows is some additional commentary on the nature of gabbi which you can safely ignore if you're not all that interested, but might be usefu:

Note that gabbi tests are not intended to be unit tests and not intended to operate in isolation. Each file is an ordered suite. Any setup (for fixtures) is done at the level of the yaml file, not per test. The tests before any one test impact that test, so you can build up a collection of resources or tell an api "story" in one file.

The tests you list above are part of gabbi using gabbi to test itself. There are other tests within the tests dir which are more explicitly unit tests (some even use mocks).

Pretty much the entire reason that gabbi exists is because mocks are a bad idea when trying to do full throated tests of HTTP APIs. The combination of gabbi and wsgi-intercept means that you're testing a real wsgi application, through real http clients, and sending back and forth real HTTP, not faking it.

**Comment by amoralej** [comment]
Thanks for you quick answer.

Yes, I think the proposed solution will work for our packaging case. I think it's a good idea to separate the tests into two different types, "pure unit tests" that shouldn't depend on external resources availability and could be used in packaging scenarios as smoke tests and full tests with a wider purpose.

**Comment by cdent** [comment]
Part of the point of gabbi is to make it easier to dissolve the arbitrary boundaries between different types of tests and just have "tests" which help developers write good code.

I agree that the tests that talk to the internet are an issue, so that will be fixed, but in general the way gabbi's own tests are structured is not going to change.

**Comment by amoralej** [comment]
ok, no problem as soon as there is an easy way to avoid dependencies on internet while testing it.
