### ISSUE TITLE
when SSL is enabled, 400 Bad Request

### ISSUE THREAD

**Issue by EmilienM** [cdent/gabbi#138]
Testing OpenStack Gnocchi Tempest tests, that run Gabbi, on SSL & IPV6 network, the Gabbi tests fail with 400 Bad Request

More details: http://logs.openstack.org/61/318961/8/check/gate-puppet-openstack-integration-3-scenario001-tempest-centos-7/5bac108/console.html#_2016-06-01_22_29_31_718

**Comment by EmilienM** [comment]
@cdent feel free to close this one if duplicated with another SSL bug. Not sure it was related though.

**Comment by cdent** [comment]
This is probably related to #50 and #105 but I'll take a look. For now the fix is likely in the gnocchi tempests themselves.

I assume it also doesn't work for SSL & IPV4?

**Comment by cdent** [comment]
#139 has the fix for this, but it will require a change in the gnocchi tests to make it work

Where it [determines the port](https://github.com/openstack/gnocchi/blob/04aab41d76b85c59f0b6a9de2bb80046ac6a1da6/gnocchi/tempest/scenario/__init__.py#L46) it will also need to decide a True or False value for `require_ssl` and then pass `require_ssl=require_ssl` as one of the args to build tests. I can do those changes once we've had a chat about it.

But only after #139 merges and is released.

**Comment by cdent** [comment]
@EmilienM the related [gnocchi fix](https://review.openstack.org/#/c/324337/).
