### ISSUE TITLE
gabbi-run does not expose failures' originating suite

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#181]
To reproduce:

```
$ python -m gabbi.runner http://example.org -- gabbi/tests/gabbits_runner/*.yaml
```

(which corresponds to `gabbi-run … -- /path/to/*.yaml`)

This results in three failures from three separate suites:

```
... ✗ expected failure

FAIL: expected failure
    Traceback (most recent call last):
    …
    AssertionError: '301' not found in ['666'], response:
    …
----------------------------------------------------------------------
Ran 1 test in 0.183s

FAILED (failures=1)
... ✗ expected success

FAIL: expected success
    Traceback (most recent call last):
    …
    AssertionError: '301' not found in ['200'], response:
    …
----------------------------------------------------------------------
Ran 1 test in 0.065s

FAILED (failures=1)
... ✗ expected success

FAIL: expected success
    Traceback (most recent call last):
    …
    AssertionError: '301' not found in ['200'], response:
    …
----------------------------------------------------------------------
Ran 1 test in 0.060s

FAILED (failures=1)
```

Other than the respective test's `name`, there's barely any indication where a failure originated.

Somewhat relatedly, there's also no summary across all suites - so a casual observer might only spot the last report, erroneously concluding there was only a single failure (or worse: if the last suite did _not_ fail, assume everything's fine).

**Comment by cdent** [comment]
It's churlish of me to say, but this is part of why I didn't implement file handling in gabbi-run in its earlier incarnations: The reporting handling gets more complicated, especially if a _large_ number of files are being used. Even if each suite prints out its name it could have scrolled off the screen ages ago.

So to fix this properly a few different changes are probably necessary:

* we need to preserve the suite name when creating the suite, by change the `test_base_name` in the call to `test_suite_from_dict` from `input` to the filename (if not using `stdin`).
* consider aggregating the success or failure of each suite for a final summary report, since we're in a loop anyway, this ought to be doable

Of course this all goes to pooh if some bright bulb decided that gabbi-run should be multi-process and results need to be accumulated for runner-per-file. _Please_ nobody go that route. If you need that use `driver.build_tests` and a concurrent testrunner.
