### ISSUE TITLE
when a fixture start_fixture raise unittest.SkipTest, this first test in suite is marker skip，but the other tests continue to run

### ISSUE THREAD

**Issue by EtheriousNatsu** [cdent/gabbi#228]
when I  user pytest  to run a yaml file， I hope when start_fixture raise unittest.SkipTest， this all tests in this yaml should marked skip， but  now only this first test marked skip， and the other tests continue to run。

**Comment by cdent** [comment]
Thanks for reporting this. The pytest handling of fixtures, especially failures in fixtures, is insufficiently tested. This will give us something to test and from the failure we ought to be able to figure out a fix.

If you are able to work on a fix yourself and make a pull request, please say so, otherwise I'll try to get to this soon.

**Comment by cdent** [comment]
@EtheriousNatsu if you can try the pull request at #229 to see if it works as you expect, that would be great.

**Comment by EtheriousNatsu** [comment]
thank you， if i need i will try， now i not use pytest to run my testcase， i write a xmlrunner to run my testcase for support Chinese
