### ISSUE TITLE
Question: Does gabbi support coverage?

### ISSUE THREAD

**Issue by noorul** [cdent/gabbi#245]
I have setup tests defined using gabbi. It is possible to generate coverage report using gabbi?

**Comment by cdent** [comment]
It is possible. Because gabbi tests run just like normal unittest when using either the unittest or pytest [loader](https://gabbi.readthedocs.io/en/latest/loader.html) you can run coverage tools as you normally would. Gabbi has coverage of itself configured in [tox.ini](https://github.com/cdent/gabbi/blob/209c87b86e990cd26598868c5c150a46d6b91ae8/tox.ini#L52).

If you are using `gabbi-run` then coverage is not an option because the tests and the server code are not in the same process.

There's also a [gabbi-demo](/cdent/gabbi-demo) repo that has an example of doing coverage that I've just recently updated to make it a bit more modern.

If this help you, please let us know and close the issue. If not, can you explain more about what you are trying to do? Thanks.

**Comment by noorul** [comment]
I am doing something like this 

coverage run --source raas -m py.test raas/tests/gabbits/live_test.py
coverage report

In the coverage report, I see that api layer has 0 coverage

**Comment by cdent** [comment]
> raas/tests/gabbits/live_test.py

Based on the name of this test, it sounds like you may be running a live server and not using the `app` argument to `py_test_generator` or `load_tests`. In which case coverage wouldn't be able to see the other process.

If not, if this code is publically available perhaps you can provide a link to it, so I can have a look to see what might be happening?

**Comment by noorul** [comment]
```
def load_tests(loader, tests, pattern):
    """Provide a TestSuite to the discovery process."""
    test_dir = os.path.join(os.path.dirname(__file__), TESTS_DIR)
    return driver.build_tests(test_dir, loader, **BUILD_TEST_ARGS)


def pytest_generate_tests(metafunc):
    test_dir = os.path.join(os.path.dirname(__file__), TESTS_DIR)
    sys.stderr.write("TEST_DIR {}".format(test_dir))
    driver.py_test_generator(test_dir, metafunc=metafunc, **BUILD_TEST_ARGS)
```

**Comment by noorul** [comment]
Yes, I am deploying the app in kubernetes and running the tests against that

**Comment by noorul** [comment]
Thank you for clarifying. Closing this.
