### ISSUE TITLE
case-insensitive headers

### ISSUE THREAD

**Issue by FND** [cdent/gabbi#55]
As far as I can tell, gabbi enforces lowercase headers:

```yaml
response_headers:
    content-type: text/html; charset=utf-8
```

```
... ✓ front page returns HTML
```

vs.

```yaml
response_headers:
    Content-Type: text/html; charset=utf-8
```

```
... E front page returns HTML

ERROR: front page returns HTML
	 "'Content-Type' header not available in response keys: dict_keys(['server', 'content-type', 'access-control-allow-origin', 'date', 'access-control-allow-credentials', 'connection', 'content-location', 'content-length', 'status'])"
```

From my perspective, the second version is more readable - so it would be nice if header name comparisons were case-insensitive.

**Comment by cdent** [comment]
If you like.

I guess I never noticed because the C and T above look like speed bumps to me so would never use. Which is odd, but :fried_shrimp: (I was going for shrug there but they don't seem to have that so fried shrimp will have to do).

This ought to be relatively easy fix, so feel free if you have the cycles.
