### ISSUE TITLE
it would be great if the name of the test method can be configured to the test_testsuite_testcase

### ISSUE THREAD

**Issue by ravichandrasadineni** [cdent/gabbi#68]
We use a custom Test Runner which use the test method name to log the results. Since the test method in all the test cases generated by the gabbi is [test_request](https://github.com/cdent/gabbi/blob/master/gabbi/case.py#L104), the logger logs it as a single test. It would be great if the test method name can be configured may be the parameter or uses the test name.

**Comment by cdent** [comment]
Your runner will be passed a reference to the HTTPTestCase object, from there you can get its name in I think two different ways:

* `test_case.test_data['name']`
* `test_case.__class__.__name__`

Would accessing those from your runner (using them to assign something) help? If you have a look at [gabbi.reporter](https://github.com/cdent/gabbi/blob/master/gabbi/reporter.py) it has some related examples.

The `test_request` thing is an artifact of the way in which metaclasses were necessary to manage the ordered listing between test cases. This means that each chunk of yaml is a TestCase instance rather than a test method inside a TestCase. I tried to do the latter but the it was too messy to do the ordering.

I've seen the problem you're describing also with one of the reporting tools in OpenStack CI and it surprises me because it appears to be making the assumption that test method names are supposed to be unique across an entire test suite, rather than unique within their class.

**Comment by ravichandrasadineni** [comment]
Thanks for the information. Ya I am facing the same problem. Test runner assumes the method names are unique. I think fixing that would be an appropriate thing to do.

**Comment by FND** [comment]
> reporting tools [...] making the assumption that test method names are [...]
> unique across an entire test suite, rather than unique within their class.

That sounds like a bug to me: It seems unrealistic to expect developers to
always use globally unique test names.

Any chance that could be fixed in said tools rather than working around it in
gabbi? (I suspect the answer is "hahahah *points finger*", but, you know... )

**Comment by cdent** [comment]
In the case I was referring to I don't even know what the tool was and given the complexity of OpenStack infrastructure I'm not super inclined to find out.

I agree with you that the bug is in those tools and there's nothing to change in gabbi related to this issue.
